name: Commitlint

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  # Job for push events only
  commitlint_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install commitlint
        run: |
          pnpm install conventional-changelog-conventionalcommits
          pnpm install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        run: npx commitlint --last --verbose

  # Job for pull request events only
  commitlint_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install commitlint
        run: |
          pnpm install conventional-changelog-conventionalcommits
          pnpm install commitlint@latest

      - name: Validate PR commits with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
